# Generated by Django 6.0.1 on 2026-05-22 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('STARTER', 'Starter'), ('GROWTH', 'Growth'), ('PRO', 'Pro')], max_length=50, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('credits', models.PositiveIntegerField()),
                ('validity_days', models.PositiveIntegerField(default=30)),
                ('offer_percent', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=1)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('CREDIT_PURCHASE', 'Credit Purchase')], default='CREDIT_PURCHASE', max_length=30)),
                ('payment_gateway', models.CharField(choices=[('RAZORPAY', 'Razorpay'), ('PAYU', 'PayU')], default='RAZORPAY', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('credits', models.PositiveIntegerField(default=0)),
                ('razorpay_order_id', models.CharField(max_length=255, unique=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('razorpay_signature', models.TextField(blank=True, null=True)),
                ('payment_mode', models.CharField(blank=True, max_length=100, null=True)),
                ('card_network', models.CharField(blank=True, max_length=50, null=True)),
                ('card_number', models.CharField(blank=True, max_length=50, null=True)),
                ('gateway_response', models.JSONField(blank=True, default=dict, null=True)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.creditplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='payments_pa_status_b6726a_idx'), models.Index(fields=['user'], name='payments_pa_user_id_3e3078_idx'), models.Index(fields=['razorpay_order_id'], name='payments_pa_razorpa_c4e21c_idx')],
            },
        ),
    ]
