# Generated by Django 6.0.1 on 2026-05-20 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0004_activesession'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generationhistory',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='generationhistory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='generationhistory',
            name='mrp',
        ),
        migrations.RemoveField(
            model_name='generationhistory',
            name='net_weight',
        ),
        migrations.RemoveField(
            model_name='generationhistory',
            name='return_price',
        ),
        migrations.AddField(
            model_name='generationhistory',
            name='categories',
            field=models.ManyToManyField(related_name='generation_histories', to='products.subsubcategory'),
        ),
        migrations.AlterField(
            model_name='generationhistory',
            name='meesho_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='generationhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='generationhistory',
            index=models.Index(fields=['created_at'], name='generation__created_91bd43_idx'),
        ),
        migrations.AddIndex(
            model_name='generationhistory',
            index=models.Index(fields=['user'], name='generation__user_id_e4980b_idx'),
        ),
        migrations.AlterModelTable(
            name='generationhistory',
            table='generation_history',
        ),
    ]
