# Generated by Django 6.0.1 on 2026-05-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0005_alter_generationhistory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyLabelSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(db_index=True, unique=True)),
                ('total_pdfs', models.IntegerField(default=0)),
                ('total_labels', models.IntegerField(default=0)),
                ('last_used', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'ordering': ['-month'],
                'indexes': [models.Index(fields=['month'], name='generator_m_month_a6368d_idx'), models.Index(fields=['-last_used'], name='generator_m_last_us_c710d2_idx')],
            },
        ),
    ]
