# Generated by Django 6.0.1 on 2026-05-22 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0006_monthlylabelsummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLabelSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('total_pdfs', models.IntegerField(default=0)),
                ('total_labels', models.IntegerField(default=0)),
                ('last_used', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AlterModelOptions(
            name='monthlylabelsummary',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='monthlylabelsummary',
            name='generator_m_month_a6368d_idx',
        ),
        migrations.RemoveIndex(
            model_name='monthlylabelsummary',
            name='generator_m_last_us_c710d2_idx',
        ),
        migrations.AddIndex(
            model_name='dailylabelsummary',
            index=models.Index(fields=['date'], name='generator_d_date_ab23bd_idx'),
        ),
        migrations.AddIndex(
            model_name='dailylabelsummary',
            index=models.Index(fields=['-last_used'], name='generator_d_last_us_a28544_idx'),
        ),
    ]
