# Generated by Django 6.0.1 on 2026-05-22 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_usercredit_balance_alter_usercredit_expires_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits', models.IntegerField()),
                ('transaction_type', models.CharField(choices=[('ADD', 'Add Credit'), ('DEDUCT', 'Deduct Credit'), ('REFUND', 'Refund Credit')], max_length=10)),
                ('previous_balance', models.IntegerField(default=0)),
                ('current_balance', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
