# Generated by Django 6.0.1 on 2026-05-22 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_credithistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credithistory',
            name='transaction_type',
            field=models.CharField(choices=[('ADD', 'Add Credit'), ('DEDUCT', 'Deduct Credit'), ('REFUND', 'Refund Credit'), ('EXPIRE', 'Expire Credit')], max_length=10),
        ),
    ]
