# Generated by Django 5.2.7 on 2026-07-19 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_deviceregistration_productreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_provider',
            field=models.CharField(choices=[('EMAIL', 'Email / Password'), ('GOOGLE', 'Google')], default='EMAIL', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='google_uid',
            field=models.CharField(blank=True, help_text='Firebase UID for users who signed up/logged in via Google.', max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture_url',
            field=models.URLField(blank=True, help_text='Google profile photo URL, if available.', max_length=500, null=True),
        ),
    ]
