# Generated by Django 6.0.1 on 2026-05-20 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='products.category')),
            ],
            options={
                'db_table': 'sub_categories',
            },
        ),
        migrations.CreateModel(
            name='SubSubCategory',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('min_products', models.IntegerField(default=1)),
                ('max_products', models.IntegerField(default=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_sub_categories', to='products.subcategory')),
            ],
            options={
                'db_table': 'sub_sub_categories',
            },
        ),
        migrations.CreateModel(
            name='SuperCategory',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'super_categories',
                'indexes': [models.Index(fields=['name'], name='super_categ_name_7d8082_idx')],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='super_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='products.supercategory'),
        ),
        migrations.AddIndex(
            model_name='subcategory',
            index=models.Index(fields=['name'], name='sub_categor_name_a8bf9b_idx'),
        ),
        migrations.AddIndex(
            model_name='subcategory',
            index=models.Index(fields=['category'], name='sub_categor_categor_e70bb6_idx'),
        ),
        migrations.AddIndex(
            model_name='subcategory',
            index=models.Index(fields=['category', 'name'], name='sub_categor_categor_0a2b8b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subcategory',
            unique_together={('category', 'name')},
        ),
        migrations.AddIndex(
            model_name='subsubcategory',
            index=models.Index(fields=['name'], name='sub_sub_cat_name_9858c1_idx'),
        ),
        migrations.AddIndex(
            model_name='subsubcategory',
            index=models.Index(fields=['sub_category'], name='sub_sub_cat_sub_cat_54a680_idx'),
        ),
        migrations.AddIndex(
            model_name='subsubcategory',
            index=models.Index(fields=['sub_category', 'name'], name='sub_sub_cat_sub_cat_20f83b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subsubcategory',
            unique_together={('sub_category', 'name')},
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='categories_name_98d7d5_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['super_category'], name='categories_super_c_7cb2c3_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['super_category', 'name'], name='categories_super_c_af9e80_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('super_category', 'name')},
        ),
    ]
